#!/usr/bin/env python3
"""Generate a compact TOOL_DEFS_JSON from AVAILABLE_TOOLS.

This script reads ALiveMCP_Remote.tools.core.registry.AVAILABLE_TOOLS and
emits a compact JSON array suitable for embedding into
`mcp_server_tool_defs.py`. By default it prints to stdout; pass `--output`
to write to a file.
"""

import argparse
import json

from ALiveMCP_Remote.tools.core import registry as registry_mod


def build_tool_defs():
    out = []
    for name in registry_mod.AVAILABLE_TOOLS:
        # Minimal placeholder description and empty schema
        desc = f"{name} - auto-generated"
        schema = {"type": "object", "properties": {}}
        out.append([name, desc, schema])
    return out


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", "-o", help="Write generated module to path")
    args = parser.parse_args()

    data = build_tool_defs()
    json_text = json.dumps(data, indent=None)

    if args.output:
        with open(args.output, "w", encoding="utf-8") as fh:
            fh.write("# Auto-generated by scripts/generate_tool_defs.py\n")
            fh.write("TOOL_DEFS_JSON = r'''\n")
            fh.write(json_text)
            fh.write("\n'''\n")
        print(f"Wrote {args.output}")
    else:
        print(json_text)


if __name__ == "__main__":
    main()
